defmodule Language do
  
  def list do
    [
      %{key: :javascript, lang: "Javascript"},
      %{key: :java, lang: "Java"} ,
      %{key: :python, lang: "Python"},
      %{key: :php, lang: "PHP"},
      %{key: :ruby, lang: "Ruby"},
      %{key: :cpp, lang: "C++"},
      %{key: :c, lang: "C"},
      %{key: :shell, lang: "Shell"},
      %{key: :csharp, lang: "C#"},      
      %{key: :objectivec, lang: "Objective-C"},
      %{key: :r, lang: "R"},
      %{key: :viml, lang: "VimL"},
      %{key: :go, lang: "Go"},
      %{key: :perl, lang: "Perl"},
      %{key: :coffeescript, lang: "CoffeeScript"},
      %{key: :tex, lang: "TeX"},
      %{key: :swift, lang: "Swift"},
      %{key: :scala, lang: "Scala"},
      %{key: :emacslisp, lang: "Emacs Lisp"},
      %{key: :haskell, lang: "Haskell"},
      %{key: :lua, lang: "Lua"},
      %{key: :clojure, lang: "Clojure"},
      %{key: :matlab, lang: "Matlab"},
      %{key: :arduino, lang: "Arduino"},
      %{key: :groovy, lang: "Groovy"},
      %{key: :puppet, lang: "Puppet"},
      %{key: :rust, lang: "Rust"},
      %{key: :powershell, lang: "PowerShell"},
      %{key: :erlang, lang: "Erlang"},
      %{key: :vb, lang: "Visual Basic"},                      
      %{key: :processing, lang: "Processing"},
      %{key: :assembly, lang: "Assembly"},
      %{key: :typescript, lang: "TypeScript"},
      %{key: :xslt, lang: "XSLT"},
      %{key: :actionscript, lang: "ActionScript"},
      %{key: :asp, lang: "ASP"},
      %{key: :ocaml, lang: "OCaml"},
      %{key: :d, lang: "D"},
      %{key: :scheme, lang: "Scheme"},      
      %{key: :dart, lang: "Dart"},      
      %{key: :commonlisp, lang: "Common Lisp"},      
      %{key: :julia, lang: "Julia"},      
      %{key: :fsharp, lang: "F#"},      
      %{key: :elixir, lang: "Elixir"},
      %{key: :fortran, lang: "Fortran"}, 
      %{key: :haxe, lang: "Haxe"}, 
      %{key: :racket, lang: "Racket"}, 
      %{key: :logos, lang: "Logos"}, 
      %{key: :kotlin, lang: "Kotlin"},      
      %{key: :pascal, lang: "Pascal"},
      %{key: :lisp, lang: "Lisp"},
      %{key: :one_c_enterprise, lang: "1C Enterprise"},           
      %{key: :apex, lang: "Apex"},
      %{key: :crystal, lang: "Crystal"},
      %{key: :ada, lang: "Ada"},
      %{key: :cobol, lang: "COBOL"},
      %{key: :modula2, lang: "Modula-2"}
    ]
  end

end
